all_for_kids_main_homepage:
    path:     /
    defaults: { _controller: AllForKidsMainBundle:Default:index }
accueil:
    path:     /Accueil
    defaults: { _controller: AllForKidsMainBundle:Accueil:Accueil }

Admin:
    path:     /Show
    defaults: { _controller: AllForKidsMainBundle:Admin:Show }

Admin2:
    path:     /admin
    defaults: { _controller: AllForKidsMainBundle:Admin:admin }



showbaby:
    path:     /ShowBaby
    defaults: { _controller: AllForKidsMainBundle:BabySitter:Show }

showPediatre:
    path:     /ShowPediatre
    defaults: { _controller: AllForKidsMainBundle:Pediatre:Show }


evenement_homepage:
    path:     /
    defaults: { _controller: AllForKidsMainBundle:Default:index }

ajout_even:
    path:     /ajoutEven
    defaults: { _controller: AllForKidsMainBundle:evenement:Ajouter }

affiche_even:
    path:     /afficherEven
    defaults: { _controller: AllForKidsMainBundle:evenement:Afficher }

supprime_even:
    path:     /supprimerEven/{id_even}
    defaults: { _controller: AllForKidsMainBundle:evenement:Supprimer }

update_even:
    path:     /updateEven/{id_even}
    defaults: { _controller: AllForKidsMainBundle:evenement:Update }


recherche_even:
    path:     /rechercheEven
    defaults: { _controller: AllForKidsMainBundle:evenement:Rechercher }


ajouter_categ:
    path:     /ajouterCateg
    defaults: { _controller: AllForKidsMainBundle:categorie:AjouterCateg }

supprime_categ:
    path:     /supprimeCateg/{id}
    defaults: { _controller: AllForKidsMainBundle:categorie:Supprimer }


affiche_categ:
    path:     /afficheCateg
    defaults: { _controller: AllForKidsMainBundle:categorie:ListeCateg }

listeEven:
    path:     /listeEven
    defaults: { _controller: AllForKidsMainBundle:evenement:Liste }


ReadMore:
    path:     /ReadMore/{id_even}
    defaults: { _controller: AllForKidsMainBundle:evenement:Read }


Map:
    path:     /Map
    defaults: { _controller: AllForKidsMainBundle:Default:map }

affiche_reservation:
    path:     /afficheReserv
    defaults: { _controller: AllForKidsMainBundle:Reservation:ListerReservation }

ajout_reservation:
    path:     /ajoutReserv/{id_even}
    defaults: { _controller: AllForKidsMainBundle:Reservation:reserv }
